name: Build PreRelease APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  BuildPreRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone mihomo kernel
        run: |
          mkdir -p core/src/foss/golang
          git clone https://github.com/MetaCubeX/mihomo core/src/foss/golang/clash
          cd core/src/foss/golang/clash
          git checkout 5184081ac327394d9e15fa5d5f9f4a61e723fd94

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon app:assemblePreRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PreRelease-APK
          path: app/build/outputs/apk/preRelease/*.apk
