name: Build Tii APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone mihomo kernel
        run: |
          mkdir -p core/src/foss/golang
          git clone https://github.com/MetaCubeX/mihomo core/src/foss/golang/clash
          cd core/src/foss/golang/clash
          git checkout 5184081ac327394d9e15fa5d5f9f4a61e723fd94

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon app:assembleAlphaRelease

      - name: Upload APK (universal)
        uses: actions/upload-artifact@v4
        with:
          name: Tii-APK-universal
          path: app/build/outputs/apk/alpha/release/*-universal-*.apk

      - name: Upload APK (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: Tii-APK-arm64-v8a
          path: app/build/outputs/apk/alpha/release/*-arm64-v8a-*.apk

      - name: Upload APK (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: Tii-APK-armeabi-v7a
          path: app/build/outputs/apk/alpha/release/*-armeabi-v7a-*.apk

      - name: Upload APK (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: Tii-APK-x86_64
          path: app/build/outputs/apk/alpha/release/*-x86_64-*.apk

      - name: Upload APK (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Tii-APK-x86
          path: app/build/outputs/apk/alpha/release/*-x86-*.apk
